### ISSUE TITLE
add these lines to your head section in html

### ISSUE THREAD

**Issue by rimmesbe** [diguinhothebest/f1-3-c2p1-colmar-academy#1]
There are 2 things you should adding into the `<head>` section:
first a reset.css file. You may notice the gap around the edge of your page, especially on mobile. That is the body tag default margin which is one thing the reset.css file will set to 0 for you.

Secondly you should add this meta tag anytime you are using media queries:
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`
This will make sure the media queries register on all devices. 
https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag

https://github.com/diguinhothebest/f1-3-c2p1-colmar-academy/blob/master/CapstoneProject/index.html#L3

**Comment by diguinhothebest** [comment]
Hi Ryan, i had added the reset.css file when i was writing the HTML but when i was trying to style it on CSS some of the positioning and the elements from h1 to h6 were not responding. The h1 and h6 were all the same size around 12px. I don't know what happened. When i removed the <link for the reset.css file everything went back to normal and i could finish the job.  
I don't really remember i had to use <meta...  when i was using media queries. 
I will correct it. Thanks,
Reis

**Comment by rimmesbe** [comment]
A lot of people like normalize.css files better that reset.css
It is very similar but keeps some default stylings that people like.

**Comment by diguinhothebest** [comment]
Great. I will try normalize.css in my next project.
Thanks.
