### ISSUE TITLE
html looks good

### ISSUE THREAD

**Issue by rimmesbe** [diguinhothebest/f1-3-c2p1-colmar-academy#2]
Your html looks really good, well organized and structured. If you want to take your html to the next level keep incorporating more semantic tags. There are many and they are a very popular trend in modern html development. Here is a good article on it:
https://www.pluralsight.com/guides/html-css/semantic-html?aid=701j0000001heIqAAI&promo=&oid=&utm_source=google&utm_medium=ppc&utm_campaign=CA_Dynamic&utm_content=&utm_term=&gclid=CjwKCAjwlrnNBRBMEiwApKU4PBiUM7wtxiyqNw-6Zoikh6ChlNul6tTL839Zj2h_JNTZcK6PE5WWlRoCiOYQAvD_BwE

https://github.com/diguinhothebest/f1-3-c2p1-colmar-academy/blob/master/CapstoneProject/index.html

**Comment by diguinhothebest** [comment]
Hi Ryan, thanks again for your feedback. I will check all content later. Quick question: When the curse is over what do you think i should do to master in Web developer? Just a little advice from an expert would help. 
Thanks,
Reis

**Comment by rimmesbe** [comment]
You mean when the cursor hovers over links? Just smooth transitions, make sure the new styling doesn't push around the other elements on the page. There are many different ways to style, more of a design topic.
