### ISSUE TITLE
css naming conventions

### ISSUE THREAD

**Issue by rimmesbe** [diguinhothebest/f1-3-c2p1-colmar-academy#3]
I would recommend avoiding position or ordering names like: .left .right .box-one, box-two etc.
This puts a positional dependency on  your classes which makes them less flexible for site layout changes and reusability. Try to name classes for the component being styled. Check out the BEM css convention: http://getbem.com/introduction/

**Comment by diguinhothebest** [comment]
Thank you so much for this advice. I was struggling to name the elements. I was even naming them in Portuguese which is my first language. I am going to check  it out later on.
