### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [diguinhothebest/f1-3-c2p1-colmar-academy#4]
Grade: Satisfactory

Summary: Nice job on this project, the site looks good on both mobile and desktop. You used a lot of good techniques and your code was well organized in both html and css. I created a few issues of techniques you can expand on to take your coding to the next level. Overall well done, hope you enjoyed the course!

**Comment by diguinhothebest** [comment]
Hi Ryan i am not feeling 100% confident yet. Do you know if i want i could start the curse all over again when it is over? I am running very late. I will be starting Bootstrap tonight 01/02 and i believe i should have done the last unit (9) by now.
Thanks,
Reis

**Comment by rimmesbe** [comment]
You will always have access to the content of the course, so feel free to refresh yourself. Make sure you at least start all the javascript projects before the end of the course so that you will maintain access.

**Comment by diguinhothebest** [comment]
ok. Thanks
